spring:
  application:
    name: myBatisDemo
  datasource:
    url: jdbc:mysql://localhost:3306/jeecg-boot?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: soiree
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 6000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*Mapper.xml

logging:
  level:
    com.*.mapper: debug