spring:
  application:
    name: demo-consumer
  cloud:
    nacos:
      server-addr: http://127.0.0.1:8848
      discovery:
        service: ${spring.application.name}
server:
  port: 28080
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
